---
skip_tags: true
cache:
  - C:\strawberry -> appveyor.yml
environment:
  nodejs_version: "6"
install:
  - if not exist "C:\strawberry" cinst strawberryperl -y
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  # Without this Data::UUID (a dep of CHI) will fail to install - https://github.com/rjbs/Data-UUID/issues/24
  - md C:\tmp
  - cpanm --installdeps --with-develop -n .
  - ps: Install-Product node $env:nodejs_version
  # See https://www.chadsikorra.com/blog/appveyor-chocolatey-php - without
  # this some of the PHP prereq packages fail to install
  - ps: Set-Service wuauserv -StartupType "Automatic"; Start-Service wuauserv
  - cinst php
build_script:
  - perl -e 1
test_script:
  - prove -lrv t/ xt/
### __app_cisetup__
# --- {}

### __app_cisetup__
